Repository exasol/virtual-schema-common-java, pull requests merged in 2019-08, with the labels that each got.

#99 Enhancement/98 use lambdas in log messsages
  pom.xml
  src/main/java/com/exasol/adapter/AdapterRegistry.java
  src/test/java/com/exasol/adapter/sql/SqlNodeTest.java
  src/test/java/com/exasol/logging/RemoteLogManagerTest.java
Labels: enhancement

#102 #239: General binary column handling
  pom.xml
  src/main/java/com/exasol/adapter/AdapterProperties.java
  src/main/java/com/exasol/adapter/BinaryColumnHandling.java
  src/test/java/com/exasol/adapter/AdapterPropertiesTest.java
Labels: feature

#104 #103: Add `DataType.isSupported`
  pom.xml
  src/main/java/com/exasol/adapter/metadata/DataType.java
  src/test/java/com/exasol/adapter/metadata/DataTypeTest.java
Labels: feature

#106 Feature/105 port to java9
  pom.xml
  src/main/java/com/exasol/adapter/metadata/SchemaMetadataInfo.java
  src/main/java/com/exasol/adapter/metadata/TableMetadata.java
  src/test/java/com/exasol/adapter/metadata/SchemaMetadataInfoTest.java
  src/test/java/com/exasol/adapter/metadata/TableMetadataTest.java
  src/test/java/com/exasol/adapter/request/parser/TablesMetadataParserTest.java
  src/test/java/com/exasol/adapter/sql/SqlNodeTest.java
Labels: refactoring

#108 #107: Update Eclipse launch files to Java 9
  launch/virtual-schema-common clean.launch
  launch/virtual-schema-common install.launch
  launch/virtual-schema-common package.launch
Labels: bug
