Repository exasol/virtual-schema-common-java, pull requests merged in 2019-06, with the labels that each got.

#84 #83: added method that get the adapter version into AdapterFactory
  pom.xml
  src/main/java/com/exasol/adapter/AdapterFactory.java
  src/main/java/com/exasol/adapter/AdapterRegistry.java
  src/test/java/com/exasol/adapter/DummyAdapterFactory.java
  src/test/java/com/exasol/adapter/RequestDispatcherTest.java
Labels: feature

#86 #85: Fall back to local logging in case debug address is invalid
  pom.xml
  src/main/java/com/exasol/adapter/metadata/SchemaMetadataPropertyConstants.java
  src/main/java/com/exasol/adapter/request/LoggingConfiguration.java
  src/test/java/com/exasol/adapter/request/LoggingConfigurationTest.java
Labels: enhancement

#88 #87: Fix Eclipse warnings in 6.0.1
  pom.xml
  src/test/java/com/exasol/adapter/sql/SqlColumnTest.java
  src/test/java/com/exasol/adapter/sql/SqlFunctionAggregateGroupConcatTest.java
  src/test/java/com/exasol/adapter/sql/SqlFunctionAggregateTest.java
  src/test/java/com/exasol/adapter/sql/SqlFunctionScalarCaseTest.java
  src/test/java/com/exasol/adapter/sql/SqlFunctionScalarCastTest.java
  src/test/java/com/exasol/adapter/sql/SqlFunctionScalarExtractTest.java
  src/test/java/com/exasol/adapter/sql/SqlFunctionScalarTest.java
  src/test/java/com/exasol/adapter/sql/SqlLimitTest.java
  src/test/java/com/exasol/adapter/sql/SqlLiteralBoolTest.java
  src/test/java/com/exasol/adapter/sql/SqlLiteralDateTest.java
  src/test/java/com/exasol/adapter/sql/SqlLiteralDoubleTest.java
  src/test/java/com/exasol/adapter/sql/SqlLiteralIntervalTest.java
  src/test/java/com/exasol/adapter/sql/SqlLiteralNullTest.java
  src/test/java/com/exasol/adapter/sql/SqlLiteralStringTest.java
  src/test/java/com/exasol/adapter/sql/SqlLiteralTimestampTest.java
  src/test/java/com/exasol/adapter/sql/SqlLiteralTimestampUtcTest.java
  src/test/java/com/exasol/adapter/sql/SqlPredicateAndTest.java
  src/test/java/com/exasol/adapter/sql/SqlPredicateBetweenTest.java
  src/test/java/com/exasol/adapter/sql/SqlPredicateEqualTest.java
  src/test/java/com/exasol/adapter/sql/SqlPredicateIsNotNullTest.java
  src/test/java/com/exasol/adapter/sql/SqlPredicateIsNullTest.java
  src/test/java/com/exasol/adapter/sql/SqlPredicateLessEqualTest.java
  src/test/java/com/exasol/adapter/sql/SqlPredicateLessTest.java
  src/test/java/com/exasol/adapter/sql/SqlPredicateLikeRegexpTest.java
  src/test/java/com/exasol/adapter/sql/SqlPredicateLikeTest.java
  src/test/java/com/exasol/adapter/sql/SqlPredicateNotEqualTest.java
  src/test/java/com/exasol/adapter/sql/SqlPredicateNotTest.java
  src/test/java/com/exasol/adapter/sql/SqlPredicateOrTest.java
  src/test/java/com/exasol/adapter/sql/SqlTableTest.java
  src/test/java/com/exasol/mocking/MockUtils.java
Labels: bug

#91 #52: SchemaMetadata JSON builder
  pom.xml
  src/main/java/com/exasol/adapter/json/SchemaMetadataSerializer.java
  src/main/java/com/exasol/adapter/json/SqlDataTypeJsonSerializer.java
  src/main/java/com/exasol/adapter/metadata/TableMetadata.java
  src/main/java/com/exasol/adapter/metadata/converter/SchemaMetadataJsonConverter.java
  src/main/java/com/exasol/adapter/response/converter/ResponseJsonConverter.java
  src/main/java/com/exasol/errorhandling/ErrorMessages.java
  src/test/java/com/exasol/adapter/json/SchemaMetadataSerializerTest.java
  src/test/java/com/exasol/adapter/json/SqlDataTypeJsonSerializerTest.java
  src/test/java/com/exasol/adapter/metadata/converter/SchemaMetadataJsonConverterTest.java
Labels: refactoring
