Repository exasol/virtual-schema-common-java, pull requests merged in 2020-12, with the labels that each got.

#192 #186: Improved the API documentation: selectList
  doc/development/api/virtual_schema_api.md
Labels: documentation

#193 #190: Fixed SELECTLIST_EXPRESSIONS documentation
  src/main/java/com/exasol/adapter/capabilities/MainCapability.java
Labels: documentation

#199 * #197: Improved AGGREGATE_GROUP_BY_COLUMN, AGGREGATE_GROUP_BY_EXPRES…
  doc/changes/changes_13.0.0.md
  src/main/java/com/exasol/adapter/capabilities/MainCapability.java
Labels: documentation

#194 Feature/188 generate explicit select list
  doc/changes/changelog.md
  doc/changes/changes_14.0.0.md
  doc/changes/changes_next.md
  pom.xml
  src/main/java/com/exasol/adapter/request/parser/PushdownSqlParser.java
  src/main/java/com/exasol/adapter/sql/SqlSelectList.java
  src/main/java/com/exasol/adapter/sql/SqlSelectListType.java
  src/test/java/com/exasol/adapter/request/parser/PushDownSqlParserTest.java
  src/test/resources/json/pushdown_request_nested_join_with_repeated_table_without_select_list.json
  src/test/resources/json/pushdown_request_nested_join_without_select_list.json
  src/test/resources/json/pushdown_request_nested_join_without_select_list_reversed.json
  src/test/resources/json/pushdown_request_simple_inner_join_with_select_list.json
  src/test/resources/json/pushdown_request_simple_inner_join_without_select_list.json
Labels: feature

#200 * #196: Added an argument validation to SqlFunctionAggregateGroupConcat builder
  doc/changes/changes_13.0.0.md
  doc/changes/changes_14.0.0.md
  src/main/java/com/exasol/adapter/sql/SqlFunctionAggregateGroupConcat.java
  src/test/java/com/exasol/adapter/sql/SqlFunctionAggregateGroupConcatTest.java
Labels: refactoring
