Repository exasol/virtual-schema-common-java, pull requests merged in 2021-02, with the labels that each got.

#210 * #209: Fixed wrong values format of literal_exactnumeric and literal…
  .github/workflows/broken_links_checker.yml
  README.md
  doc/changes/changes_14.0.1.md
  doc/development/api/virtual_schema_api.md
  src/main/java/com/exasol/adapter/sql/SqlLiteralDouble.java
  src/main/java/com/exasol/adapter/sql/SqlLiteralExactnumeric.java
  src/test/java/com/exasol/adapter/request/parser/PushDownSqlParserTest.java
  src/test/java/com/exasol/adapter/sql/SqlLiteralDoubleTest.java
Labels: bug

#207 Refactor building phase of the application
  doc/changes/changelog.md
  doc/changes/changes_14.0.1.md
  doc/changes/changes_15.0.0.md
  pom.xml
  src/main/java/com/exasol/adapter/AdapterCallExecutor.java
  src/main/java/com/exasol/adapter/AdapterFactory.java
  src/main/java/com/exasol/adapter/AdapterRegistry.java
  src/main/java/com/exasol/adapter/RequestDispatcher.java
  src/main/java/com/exasol/adapter/VirtualSchemaAdapter.java
  src/test/java/com/exasol/adapter/AdapterCallExecutorTest.java
  src/test/java/com/exasol/adapter/AdapterRegistryTest.java
  src/test/java/com/exasol/adapter/DummyAdapterFactory.java
  src/test/java/com/exasol/adapter/RequestDispatcherTest.java
  src/test/java/com/exasol/adapter/StubAdapter.java
  src/test/resources/META-INF/services/com.exasol.adapter.AdapterFactory
  src/test/resources/META-INF/services/com.exasol.adapter.VirtualSchemaAdapter
Labels: refactoring

#212 Remove 'AdapterName' from 'AdapterRequest'
  doc/changes/changes_15.0.0.md
  src/main/java/com/exasol/adapter/metadata/SchemaMetadataInfo.java
  src/main/java/com/exasol/adapter/request/AbstractAdapterRequest.java
  src/main/java/com/exasol/adapter/request/AdapterRequest.java
  src/main/java/com/exasol/adapter/request/CreateVirtualSchemaRequest.java
  src/main/java/com/exasol/adapter/request/DropVirtualSchemaRequest.java
  src/main/java/com/exasol/adapter/request/GetCapabilitiesRequest.java
  src/main/java/com/exasol/adapter/request/PushDownRequest.java
  src/main/java/com/exasol/adapter/request/RefreshRequest.java
  src/main/java/com/exasol/adapter/request/SetPropertiesRequest.java
  src/main/java/com/exasol/adapter/request/parser/RequestParser.java
  src/main/java/com/exasol/adapter/request/parser/RequestParserConstants.java
  src/test/java/com/exasol/adapter/AdapterCallExecutorTest.java
  src/test/java/com/exasol/adapter/request/DummyRequest.java
  src/test/java/com/exasol/adapter/request/RefreshRequestTest.java
  src/test/java/com/exasol/adapter/request/parser/RequestParserTest.java
Labels: refactoring

#213 * #205: Removed code duplication in the AdapterCallExecutor.
  doc/changes/changes_15.0.0.md
  src/main/java/com/exasol/adapter/AdapterCallExecutor.java
  src/main/java/com/exasol/adapter/request/AdapterRequest.java
  src/main/java/com/exasol/adapter/request/CreateVirtualSchemaRequest.java
  src/main/java/com/exasol/adapter/request/DropVirtualSchemaRequest.java
  src/main/java/com/exasol/adapter/request/GetCapabilitiesRequest.java
  src/main/java/com/exasol/adapter/request/PushDownRequest.java
  src/main/java/com/exasol/adapter/request/RefreshRequest.java
  src/main/java/com/exasol/adapter/request/SetPropertiesRequest.java
Labels: refactoring

#214 Refactored building phase of the application left overs
  doc/changes/changes_15.0.0.md
  src/main/java/com/exasol/adapter/AdapterFactory.java
  src/main/java/com/exasol/adapter/RequestDispatcher.java
  src/main/java/com/exasol/adapter/VirtualSchemaAdapter.java
  src/test/java/com/exasol/adapter/StubAdapter.java
  src/test/java/com/exasol/adapter/StubAdapterFactory.java
  src/test/resources/META-INF/services/com.exasol.adapter.AdapterFactory
  src/test/resources/META-INF/services/com.exasol.adapter.VirtualSchemaAdapter
Labels: refactoring

#215 * #186: Updated select list API description.
  doc/changes/changes_15.0.0.md
  doc/development/api/virtual_schema_api.md
Labels: documentation

#217 Removed `SQL_DIALECT_PROPERTY` from `AdapterProperties`
  doc/changes/changelog.md
  doc/changes/changes_15.0.1.md
  launch/virtual-schema-common all tests.launch
  pom.xml
  src/main/java/com/exasol/adapter/AdapterProperties.java
  src/test/java/com/exasol/adapter/AdapterPropertiesTest.java
  src/test/java/com/exasol/adapter/RequestDispatcherTest.java
  src/test/java/com/exasol/adapter/request/parser/RequestParserTest.java
Labels: refactoring

#220 * #219: Moved Double and Exactnumeric formatting to the JDBC part of …
  doc/changes/changes_15.0.1.md
  src/main/java/com/exasol/adapter/sql/SqlLiteralDouble.java
  src/main/java/com/exasol/adapter/sql/SqlLiteralExactnumeric.java
  src/test/java/com/exasol/adapter/request/parser/PushDownSqlParserTest.java
  src/test/java/com/exasol/adapter/sql/SqlLiteralDoubleTest.java
Labels: refactoring
